version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-Backend
    container_name: backend_container
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - backend_network

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend_network

  frontend:
    build:
      context: .  # Directory where your frontend code is located
      dockerfile: Dockerfile-Frontend  # Use a custom Dockerfile for frontend (React/Vite)
    container_name: frontend-container
    ports:
      - "80:80"  # Expose the port Nginx listens to
    networks:
      - frontend_network

  # Nginx service to serve the frontend
  nginx:
    image: nginx:alpine
    container_name: nginx-container
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf  # Your Nginx config file
      - ./frontend/build:/usr/share/nginx/html  # Build folder from React/Vite
    ports:
      - "8080:80"  # Expose port 80 to access the frontend
    networks:
      - frontend_network

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
