# Stage 1: Build React/Vite project
FROM node:20 as build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY ./Frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend files
COPY ./Frontend /app

# Build the React/Vite project
RUN npm run build

