services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-Backend
    container_name: backend_container
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      backend_network:
        ipv4_address: 172.20.0.10
    env_file:
      - /Backend/.env
    dns:
      - 172.20.0.12
      - 8.8.8.8
      - 1.1.1.1

  mongo:
    restart: always
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      backend_network:
        ipv4_address: 172.20.0.11
  nginx:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-Frontend
    container_name: nginx_container
    ports:
      - "80:80"
    networks:
      backend_network:
        ipv4_address: 172.20.0.13
    dns:
      - 172.20.0.12

  bind9:
    build:
      context: .
      dockerfile: Dockerfile-Bind
    container_name: bind_container
    image: custom-bind9
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      - BIND9_USER=root
    volumes:
      - ./bind/config:/etc/bind
      - ./bind/cache:/var/cache/bind
      - ./bind/records:/var/lib/bind
      - ./bind/log:/var/log/named
    restart: unless-stopped
    networks:
      backend_network:
        ipv4_address: 172.20.0.12

networks:
  backend_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
volumes:
  mongo-data:
    driver: local