FROM node:20 AS builder
WORKDIR /app

COPY ./Frontend/package*.json ./
RUN npm install

COPY ./Frontend ./
RUN npm run build  # outputs to /app/dist

# Step 2: Serve with Nginx
FROM nginx:alpine
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]